#!/usr/bin/env bash

# check if running as root user
if [ "$EUID" -ne 0 ]; then
	echo -e "This script needs to run as root user, please use \"sudo ./install\" instead";
	exit 1;
fi



# check if plymouth themes directory exists
if [ ! -d "/usr/share/plymouth/themes" ]; then
	echo -e "\"/usr/share/plymouth/themes\" directory does not exist, are you sure plymouth is installed and up to date?";
	exit 1;
fi



# coping theme in /usr/share/plymouth/themes/
echo -n "Copying theme                                                       " ;
cp -r `dirname $0`/globe /usr/share/plymouth/themes/ ;
if [ $? -gt 0 ]; then
	echo -e "\nan error occoured in moving `dirname $0`/globe to /usr/share/plymouth/themes/" ;
	exit 1;
fi
echo "[OK]" ;



# adding globe in the list of aviable themes
echo -n "Updating alternatives                                               " ;
update-alternatives --install /usr/share/plymouth/themes/default.plymouth default.plymouth /usr/share/plymouth/themes/globe/globe.plymouth 100  &> /dev/null ;
if [ $? -gt 0 ]; then
	echo -e "\nan error occurred installing alternative in /usr/share/plymouth/themes/default.plymouth" ;
	exit 1;
fi
echo "[OK]" ;



# setting globe as default plymouth theme;
echo -n "Setting new default plymouth theme                                  " ;
update-alternatives --set default.plymouth /usr/share/plymouth/themes/globe/globe.plymouth  &> /dev/null ;
if [ $? -gt 0 ]; then
	echo -e "\nan error occurred setting alternative in /usr/share/plymouth/themes/default.plymouth";
	exit 1;
fi
echo "[OK]" ;



# updating Initial RAM File System
echo -n "Updating Initial RAM File System                                    " ;
update-initramfs -u &> /dev/null ;
if [ $? -gt 0 ]; then
	echo -e "\nan error occurred executing \"update-initramfs -u\"";
	exit 1;
fi
echo "[OK]" ;



echo "globe is your plymouth theme now :)" ;



exit 0;
